name: api-server
services:
  postgres:
   image: postgres:18-bookworm 
   container_name: env-postgres
   environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
   volumes:
    - ${PROJECT_ROOT}/out/pgdata:/var/lib/postgresql
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.4
    container_name: go-cash-redis
    volumes:
      - ${PROJECT_ROOT}/out/redisdata:/data
    environment:
      - MAX_MEMORY=${MAX_MEMORY:-100mb}
    command:
      - redis-server
      - --maxmemory-policy
      - allkeys-lru
      - --maxmemory
      - ${MAX_MEMORY}
  clickhouse:
    image: clickhouse/clickhouse-server:22.10
    container_name: env-clickhouse
    user: "101:101"
    volumes:
      - "${PROJECT_ROOT}/out/clickhousedata:/var/lib/clickhouse"
      #- "${PROJECT_ROOT}/repository/config.xml:/config.xml:ro"
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB} 
      - CLICKHOUSE_CONFIG=/config.xml
    command: ["clickhouse-server"]
    restart: always

  migrate:
    image: migrate/migrate:v4.19.1
    volumes:
    - ${PROJECT_ROOT}/migrations:/migrations

  multi-forwarder:
    image: threatpatrols/multi-socat
    environment:
      MULTI_SOCAT_01: "TCP-LISTEN:5432,reuseaddr,fork TCP:postgres:5432"   # postgres port
      MULTI_SOCAT_02: "TCP-LISTEN:6379,reuseaddr,fork TCP:redis:6379"      # redis port
      MULTI_SOCAT_03: "TCP-LISTEN:8123,reuseaddr,fork TCP:clickhouse:8123" # clickhouse port HTTP-интерфейс (для API запросов, Grafana, curl)
      MULTI_SOCAT_04: "TCP-LISTEN:9000,reuseaddr,fork TCP:clickhouse:9000" # clickhouse port Нативный TCP-протокол (для clickhouse-client)
      MULTI_SOCAT_05: "TCP-LISTEN:9444,reuseaddr,fork TCP:clickhouse:9444" # clickhouse port HTTPS-интерфейс 
    ports:
      - "127.0.0.1:5432:5432"
      - "127.0.0.1:6379:6379"
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9444:9444"