services:
  postgres:
   image: postgres:18-bookworm 
   container_name: env-postgres
   environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_DB=${POSTGRES_DB}
   volumes:
    - ./out/pgdata:/var/lib/postgresql
   ports:
   - "5432:5432" #Временно не для деплоя 
   restart: always
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.4
    container_name: go-cash-redis
    ports:
      - "6379:6379"
    volumes:
      - ./out/redisdata:/data
    environment:
      - MAX_MEMORY=${MAX_MEMORY:-100mb}
    command:
      - redis-server
      - --maxmemory-policy
      - allkeys-lru
      - --maxmemory
      - ${MAX_MEMORY}
  clickhouse:
    image: clickhouse/clickhouse-server:22.10
    container_name: env-clickhouse
    user: "101:101"
    ports:
      - "8123:8123"   # HTTP-интерфейс (для API запросов, Grafana, curl)
      - "9000:9000"   # Нативный TCP-протокол (для clickhouse-client)
      - "9444:9444"   # HTTPS-интерфейс (опционально)
    volumes:
      - "./out/clickhousedata:/var/lib/clickhouse"
      - "./repository/config.xml:/config.xml:ro"
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB} 
      - CLICKHOUSE_CONFIG=/config.xml
    command: ["clickhouse-server"]
    restart: always

  postgres-migrate:
    image: migrate/migrate:v4.19.1
    volumes:
    - ./migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: bot-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:bot-postgres:5432
    ports:
    - "127.0.0.1:5432:5432"